"""Initial schema

Revision ID: 4926ab8d65bc
Revises: 
Create Date: 2026-07-23 16:23:42.317162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4926ab8d65bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.alter_column('event_registrations', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'CONFIRMED'::character varying"))
    op.alter_column('event_registrations', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_registrations', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_event_registrations_razorpay_order_id'), 'event_registrations', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_team_id'), 'event_registrations', ['team_id'], unique=False)
    op.create_foreign_key(None, 'event_registrations', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'event_registrations', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event_registrations', 'users', ['user_id'], ['id'])
    op.alter_column('events', 'requires_team',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'max_team_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('events', 'has_food',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'teams', 'users', ['leader_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'events', ['event_id'], ['id'])
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.alter_column('events', 'has_food',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('events', 'max_team_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('events', 'requires_team',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_index(op.f('ix_event_registrations_team_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_razorpay_order_id'), table_name='event_registrations')
    op.alter_column('event_registrations', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event_registrations', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event_registrations', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'CONFIRMED'::character varying"))
    op.drop_column('event_registrations', 'razorpay_order_id')
    # ### end Alembic commands ###
